# Generated by Django 5.0.1 on 2024-01-29 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopclient',
            name='balance',
            field=models.BigIntegerField(default=0, verbose_name='Баланс'),
        ),
        migrations.AlterField(
            model_name='shopclient',
            name='avatar',
            field=models.ImageField(null=True, upload_to='users/', verbose_name='Аватар'),
        ),
    ]
