version: "4.2"
services:
  django:
    build: .
    container_name: django
    restart: always
    ports:
      - 8000:8000
    volumes:
      - .:/shop/
    environment:
      - DB_NAME=djangoshop
      - DB_USER=root
      - DB_PASSWD=root
      - DB_HOST=postgres
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: postgres:16.2-alpine3.19
    volumes:
      - pgdata:/var/lib/postgresql/data/pgadata
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=djangoshop
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

volumes:
  pgdata:
