# Generated by Django 5.0.1 on 2024-02-10 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0002_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rate',
            field=models.IntegerField(default=0, max_length=5, verbose_name='Рейтинг'),
        ),
    ]
