# Generated by Django 5.0.1 on 2024-02-10 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0006_alter_rating_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testrating', to='purchases.product')),
                ('rating', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='purchases.comments')),
            ],
        ),
    ]
