# Generated by Django 5.0.1 on 2024-02-10 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0007_testrating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testrating',
            name='product',
        ),
        migrations.RemoveField(
            model_name='testrating',
            name='rating',
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
        migrations.DeleteModel(
            name='TestRating',
        ),
    ]
